<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Abhiram.Abstractions.Logging" />
        <PackageReference Include="Abhiram.Extensions.DotEnv" />
        <PackageReference Include="Abhiram.Secrets.Providers" />
        <PackageReference Include="MongoDB.Driver" />
        <PackageReference Include="Abhiram.Secrets.Providers" />
    </ItemGroup>

    <ItemGroup>
        <Content Include=".googlecloud\cloudbuild.yaml" />
    </ItemGroup>

</Project>
