@host=localhost
@port=3000
@url=api/transactions

### POST request to create a transaction
POST http://{{host}}:{{port}}/{{url}}
Content-Type: application/json

{
    "amount": 100.12,
    "description": "Milk and vegetables",
    "date": "2026-09-10",
    "from_bank": null,
    "to_bank": null,
    "category_id": "6aa6459745149dfcd5592b7d",
    "type": 1,
    "due_id": null
}
###