name: Budget-Tracker build

on:
    pull_request:
        branches:
            - main
                
jobs:
    build:
        runs-on: ubuntu-20.04
            
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '8.0.x'
                
            - name: Restore dependencies
              run: dotnet restore
              
            - name: Build
              run: dotnet build
              
            - name: Test
              run: dotnet test
              env:
                  PORT: ${{secrets.PORT}}
                  HOST: ${{secrets.HOST}}
                  DB: ${{secrets.DB}}
                  PASSWORD: ${{secrets.PASSWORD}}
                  USERNAME: ${{secrets.USERNAME}}
                  API_KEY: ${{secrets.API_KEY}}
                  ENV: ${{secrets.ENV}}
                  
            - name: Setup Docker build
              uses: docker/setup-buildx-action@v2
              
            - name: Login to Github container registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  
            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: ./Budget-Tracker # Context is the main project directory.
                  file: ./Budget-Tracker/Dockerfile # Path to your Dockerfile.
                  push: true
                  tags: ghcr.io/init:${{ github.sha }}