name: Budget-Tracker build

on:
    pull_request:
        branches:
            - main
                
jobs:
    build:
        runs-on: ubuntu-latest
            
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '8.0.x'
                
            - name: Restore dependencies
              run: dotnet restore
              
            - name: Build
              run: dotnet build
              
            - name: Test
              run: dotnet test ./IntegrationTests/IntegrationTests.csproj
              env:
                  PORT: ${{secrets.PORT}}
                  HOST: ${{secrets.HOST}}
                  DB: ${{secrets.DB}}
                  PASSWORD: ${{secrets.PASSWORD}}
                  USERNAME: ${{secrets.USERNAME}}
                  API_KEY: ${{secrets.API_KEY}}
                  ENV: ${{secrets.ENV}}